### ISSUE TITLE
DM-3212 Rescue

### ISSUE THREAD

**Issue by sebastienPoussard** [puckk/CJMCU-3212#4]
Greetings,

I did some wrong manipulations on  my DM-3212. 
When i plug  the badusb, my os (Debian) doesn' recognize it through lsusb command.
No information in the kernel neither (dmesg command)

But when i press the reset button and quickly type lsusb, the systeme recognize it.
in the kernel i see the following : 

```
usb 1-2: new full-speed USB device number 102 using xhci_hcd  
usb 1-2: New USB device found, idVendor=2341, idProduct=0036, bcdDevice= 0.01                                        
usb 1-2: New USB device strings: Mfr=2, Product=1, SerialNumber=0  
usb 1-2: Product: Arduino Leonardo  
usb 1-2: Manufacturer: Arduino LLC  
cdc_acm 1-2:1.0: ttyACM0: USB ACM device  
usb 1-2: USB disconnect, device number 102  
```

sometimes (but not always) followed with 
```
xhci_hcd 0000:00:14.0: WARN Cannot submit Set TR Deq Ptr  
xhci_hcd 0000:00:14.0: A Set TR Deq Ptr command is pending.  
xhci_hcd 0000:00:14.0: WARN Set TR Deq Ptr cmd failed due to incorrect slot or ep state.
```

Arduido IDE detect for a short moment the port.
The device quiclky go off and I doesn't have the time to do anything.

Unfortunately i just started messing with this kind of hardware and my knowledge is limited in this area, i would greatly appreciate any advice.
any ideas ?

Best regards.

**Comment by aaa3a3a** [comment]
same thing here but with windows

**Comment by HellGateCorp** [comment]
Unpack the File I put in that comment, open Arduino IDE, Select "File" -> "Open" and select your unpacked "esprogrammer8622.ino" Sketch File, now you go to the Toolbelt and the Option "Board :" and use the "Arduino Leonard" one. Compile and flash it with your Arduino IDE while you simultaneously click the Reset Button for the Bootloader and Flash command in the IDE, the timing is important check it out while do it. After this process your Port should be always there.

Greetz 

[esp8266Programmer.zip](https://github.com/puckk/CJMCU-3212/files/8209522/esp8266Programmer.zip)
